// src/app/terms-of-use/page.tsx
export default function TermsOfUse() {
    return (
        <main className="min-h-screen bg-white py-20 px-3 sm:px-5 lg:px-7">
            <div className="max-w-2xl mx-auto prose prose-slate">
                <h1 className="text-2xl font-bold text-slate-900 mb-7">Terms of Use</h1>
                <p className="text-slate-600 mb-3">Last updated: December 6, 2025</p>

                <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">1. Agreement to Terms</h2>
                <p className="text-slate-600 mb-4">
                    These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and Cardforyou ("we," "us" or "our"), concerning your access to and use of our website.
                </p>

                <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">2. Intellectual Property Rights</h2>
                <p className="text-slate-600 mb-4">
                    Unless otherwise indicated, the Site is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the "Content") and the trademarks, service marks, and logos contained therein (the "Marks") are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws.
                </p>

                <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">3. User Representations</h2>
                <p className="text-slate-600 mb-4">
                    By using the Site, you represent and warrant that:
                </p>
                <ul className="list-disc pl-5 text-slate-600 mb-4 space-y-2">
                    <li>All registration information you submit will be true, accurate, current, and complete.</li>
                    <li>You will maintain the accuracy of such information and promptly update such registration information as necessary.</li>
                    <li>You have the legal capacity and you agree to comply with these Terms of Use.</li>
                    <li>You are not a minor in the jurisdiction in which you reside.</li>
                </ul>
            </div>
        </main>
    );
}

// svelte-migration/src/routes/terms-of-use/+page.svelte
<main class="min-h-screen bg-white py-20 px-3 sm:px-5 lg:px-7">
    <div class="max-w-2xl mx-auto prose prose-slate">
        <h1 class="text-2xl font-bold text-slate-900 mb-7">Terms of Use</h1>
        <p class="text-slate-600 mb-3">Last updated: December 6, 2025</p>

        <h2 class="text-xl font-semibold text-slate-900 mt-8 mb-4">
            1. Agreement to Terms
        </h2>
        <p class="text-slate-600 mb-4">
            These Terms of Use constitute a legally binding agreement made
            between you, whether personally or on behalf of an entity ("you")
            and Cardforyou ("we," "us" or "our"), concerning your access to and
            use of our website.
        </p>

        <h2 class="text-xl font-semibold text-slate-900 mt-8 mb-4">
            2. Intellectual Property Rights
        </h2>
        <p class="text-slate-600 mb-4">
            Unless otherwise indicated, the Site is our proprietary property and
            all source code, databases, functionality, software, website
            designs, audio, video, text, photographs, and graphics on the Site
            (collectively, the "Content") and the trademarks, service marks, and
            logos contained therein (the "Marks") are owned or controlled by us
            or licensed to us, and are protected by copyright and trademark
            laws.
        </p>

        <h2 class="text-xl font-semibold text-slate-900 mt-8 mb-4">
            3. User Representations
        </h2>
        <p class="text-slate-600 mb-4">
            By using the Site, you represent and warrant that:
        </p>
        <ul class="list-disc pl-5 text-slate-600 mb-4 space-y-2">
            <li>
                All registration information you submit will be true, accurate,
                current, and complete.
            </li>
            <li>
                You will maintain the accuracy of such information and promptly
                update such registration information as necessary.
            </li>
            <li>
                You have the legal capacity and you agree to comply with these
                Terms of Use.
            </li>
            <li>
                You are not a minor in the jurisdiction in which you reside.
            </li>
        </ul>
    </div>
</main>
