// src/routes/privacy-policy/+page.svelte
<main class="min-h-screen bg-white py-20 px-3 sm:px-5 lg:px-7">
    <div class="max-w-2xl mx-auto prose prose-slate">
        <h1 class="text-2xl font-bold text-slate-900 mb-7">Privacy Policy</h1>
        <p class="text-slate-600 mb-3">Last updated: December 6, 2025</p>

        <h2 class="text-xl font-semibold text-slate-900 mt-8 mb-4">
            1. Introduction
        </h2>
        <p class="text-slate-600 mb-4">
            Welcome to Cardforyou. We respect your privacy and are committed to
            protecting your personal data. This privacy policy will inform you
            as to how we look after your personal data when you visit our
            website and tell you about your privacy rights and how the law
            protects you.
        </p>

        <h2 class="text-xl font-semibold text-slate-900 mt-8 mb-4">
            2. Data We Collect
        </h2>
        <p class="text-slate-600 mb-4">
            We may collect, use, store and transfer different kinds of personal
            data about you which we have grouped together follows:
        </p>
        <ul class="list-disc pl-5 text-slate-600 mb-4 space-y-2">
            <li>
                <strong>Identity Data</strong> includes first name, last name, username
                or similar identifier.
            </li>
            <li>
                <strong>Contact Data</strong> includes email address and telephone
                number.
            </li>
            <li>
                <strong>Technical Data</strong> includes internet protocol (IP) address,
                browser type and version, time zone setting and location, browser
                plug-in types and versions, operating system and platform, and other
                technology on the devices you use to access this website.
            </li>
        </ul>

        <h2 class="text-xl font-semibold text-slate-900 mt-8 mb-4">
            3. How We Use Your Data
        </h2>
        <p class="text-slate-600 mb-4">
            We will only use your personal data when the law allows us to. Most
            commonly, we will use your personal data in the following
            circumstances:
        </p>
        <ul class="list-disc pl-5 text-slate-600 mb-4 space-y-2">
            <li>
                Where we need to perform the contract we are about to enter into
                or have entered into with you.
            </li>
            <li>
                Where it is necessary for our legitimate interests (or those of
                a third party) and your interests and fundamental rights do not
                override those interests.
            </li>
            <li>Where we need to comply with a legal obligation.</li>
        </ul>
    </div>
</main>

// src/app/privacy-policy/page.tsx
export default function PrivacyPolicy() {
    return (
        <main className="min-h-screen bg-white py-20 px-3 sm:px-5 lg:px-7">
            <div className="max-w-2xl mx-auto prose prose-slate">
                <h1 className="text-2xl font-bold text-slate-900 mb-7">Privacy Policy</h1>
                <p className="text-slate-600 mb-3">Last updated: December 6, 2025</p>

                <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">1. Introduction</h2>
                <p className="text-slate-600 mb-4">
                    Welcome to Cardforyou. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website and tell you about your privacy rights and how the law protects you.
                </p>

                <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">2. Data We Collect</h2>
                <p className="text-slate-600 mb-4">
                    We may collect, use, store and transfer different kinds of personal data about you which we have grouped together follows:
                </p>
                <ul className="list-disc pl-5 text-slate-600 mb-4 space-y-2">
                    <li><strong>Identity Data</strong> includes first name, last name, username or similar identifier.</li>
                    <li><strong>Contact Data</strong> includes email address and telephone number.</li>
                    <li><strong>Technical Data</strong> includes internet protocol (IP) address, browser type and version, time zone setting and location, browser plug-in types and versions, operating system and platform, and other technology on the devices you use to access this website.</li>
                </ul>

                <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">3. How We Use Your Data</h2>
                <p className="text-slate-600 mb-4">
                    We will only use your personal data when the law allows us to. Most commonly, we will use your personal data in the following circumstances:
                </p>
                <ul className="list-disc pl-5 text-slate-600 mb-4 space-y-2">
                    <li>Where we need to perform the contract we are about to enter into or have entered into with you.</li>
                    <li>Where it is necessary for our legitimate interests (or those of a third party) and your interests and fundamental rights do not override those interests.</li>
                    <li>Where we need to comply with a legal obligation.</li>
                </ul>
            </div>
        </main>
    );
}
